// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qualifier.Repository;

namespace Qualifier.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200305162339_AddTripsAndTripDetails")]
    partial class AddTripsAndTripDetails
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Qualifier.Repository.Entities.TaxiEntity", b =>
                {
                    b.Property<int>("TaxiId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarPlate")
                        .HasMaxLength(9);

                    b.HasKey("TaxiId");

                    b.ToTable("Taxis");
                });

            modelBuilder.Entity("Qualifier.Repository.Entities.TripDetailEntity", b =>
                {
                    b.Property<int>("TripDetailId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int?>("TripId");

                    b.HasKey("TripDetailId");

                    b.HasIndex("TripId");

                    b.ToTable("TripDetails");
                });

            modelBuilder.Entity("Qualifier.Repository.Entities.TripEntity", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndDate");

                    b.Property<float>("Qaulification");

                    b.Property<string>("Remarks");

                    b.Property<string>("Source")
                        .HasMaxLength(100);

                    b.Property<string>("SourceLatitude");

                    b.Property<string>("SourceLongitude");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("Target")
                        .HasMaxLength(100);

                    b.Property<string>("TargetLatitude");

                    b.Property<string>("TargetLongitude");

                    b.Property<int?>("TaxiId");

                    b.HasKey("TripId");

                    b.HasIndex("TaxiId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Qualifier.Repository.Entities.TripDetailEntity", b =>
                {
                    b.HasOne("Qualifier.Repository.Entities.TripEntity", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId");
                });

            modelBuilder.Entity("Qualifier.Repository.Entities.TripEntity", b =>
                {
                    b.HasOne("Qualifier.Repository.Entities.TaxiEntity", "Taxi")
                        .WithMany()
                        .HasForeignKey("TaxiId");
                });
#pragma warning restore 612, 618
        }
    }
}
